-- MySQL Script generated by MySQL Workbench
-- Thu Jul  8 12:41:31 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`locations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`locations` ;

CREATE TABLE IF NOT EXISTS `mydb`.`locations` (
  `location_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(85) NOT NULL,
  PRIMARY KEY (`location_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`routes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`routes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`routes` (
  `route_id` INT NOT NULL AUTO_INCREMENT,
  `to_id` INT NOT NULL,
  `from_id` INT NOT NULL,
  `cost` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`route_id`),
  INDEX `fk_routes_locations_idx` (`to_id` ASC) VISIBLE,
  INDEX `fk_routes_locations1_idx` (`from_id` ASC) VISIBLE,
  CONSTRAINT `fk_routes_locations`
    FOREIGN KEY (`to_id`)
    REFERENCES `mydb`.`locations` (`location_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_routes_locations1`
    FOREIGN KEY (`from_id`)
    REFERENCES `mydb`.`locations` (`location_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`problems`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`problems` ;

CREATE TABLE IF NOT EXISTS `mydb`.`problems` (
  `problem_id` INT NOT NULL AUTO_INCREMENT,
  `to_id` INT NOT NULL,
  `from_id` INT NOT NULL,
  PRIMARY KEY (`problem_id`),
  INDEX `fk_problems_locations1_idx` (`to_id` ASC) VISIBLE,
  INDEX `fk_problems_locations2_idx` (`from_id` ASC) VISIBLE,
  CONSTRAINT `fk_problems_locations1`
    FOREIGN KEY (`to_id`)
    REFERENCES `mydb`.`locations` (`location_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_problems_locations2`
    FOREIGN KEY (`from_id`)
    REFERENCES `mydb`.`locations` (`location_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`solutions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`solutions` ;

CREATE TABLE IF NOT EXISTS `mydb`.`solutions` (
  `solution_id` INT NOT NULL AUTO_INCREMENT,
  `cost` INT NULL,
  PRIMARY KEY (`solution_id`),
  CONSTRAINT `fk_solutions_problems`
    FOREIGN KEY (`solution_id`)
    REFERENCES `mydb`.`problems` (`problem_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
