#!/bin/bash
javac -sourcepath ./src/ -d ./build/classes/ -cp ./libs/commons-lang-2.6.jar:./libs/gson.jar: src/main/java/com/example/unit1/Main.java
java -cp build/classes/:./libs/commons-lang-2.6.jar:./libs/gson.jar:. main/java/com/example/unit1/Main
